name = "Detectability"
uuid = "bf50e460-2700-4654-b9c6-67f39d124f3c"
authors = ["Niels de Koeijer"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
